# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: acmcloudlausd
service: backend-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: 'us-west-1'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  serverless-offline:
    httpPort: 8080
    host: localhost
