service: find-a-tutor-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: 'us-west-1'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0
