# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: lausd-project
service: backend-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: 'us-west-1'

functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true