# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: lausd-project
service: backend-api

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: 'us-west-1'
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: production
    FRONTEND_URL: ${env:FRONTEND_URL, 'http://localhost:3000'}

custom:
  typescript:
    webpack: false
    includeModules: true

package:
  patterns:
    - '!node_modules/.prisma/**'
    - '!node_modules/@prisma/engines/**'
    - '!tests/**'
    - '!src/**/*.test.ts'
    - '!src/**/*.spec.ts'

functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true